Paranoid_loot_table = {
{["itemid"] = 16818, ["itemname"] = "Gürtel des Netherwinds", ["dkp"] = "60",},
{["itemid"] = 16832, ["itemname"] = "Blutfangschiftung", ["dkp"] = "60",},
{["itemid"] = 16897, ["itemname"] = "Brustschutz des Stormrage", ["dkp"] = "60",},
{["itemid"] = 16898, ["itemname"] = "Stiefel des Stormrage", ["dkp"] = "60",},
{["itemid"] = 16899, ["itemname"] = "Handschützer des Stormrage", ["dkp"] = "60",},
{["itemid"] = 16902, ["itemname"] = "Schulterstücke des Stormrage", ["dkp"] = "60",},
{["itemid"] = 16903, ["itemname"] = "Gürtel des Stormrage", ["dkp"] = "60",},
{["itemid"] = 16904, ["itemname"] = "Armschienen des Stormrage", ["dkp"] = "60",},
{["itemid"] = 16905, ["itemname"] = "Blutfangbrustharnisch", ["dkp"] = "60",},
{["itemid"] = 16906, ["itemname"] = "Blutfangstiefel", ["dkp"] = "60",},
{["itemid"] = 16907, ["itemname"] = "Blutfanghandschuhe", ["dkp"] = "60",},
{["itemid"] = 16910, ["itemname"] = "Blutfanggürtel", ["dkp"] = "60",},
{["itemid"] = 16911, ["itemname"] = "Blutfangarmschienen", ["dkp"] = "60",},
{["itemid"] = 16912, ["itemname"] = "Stiefel des Netherwinds", ["dkp"] = "60",},
{["itemid"] = 16913, ["itemname"] = "Handschuhe des Netherwinds", ["dkp"] = "60",},
{["itemid"] = 16916, ["itemname"] = "Roben des Netherwinds", ["dkp"] = "60",},
{["itemid"] = 16917, ["itemname"] = "Mantel des Netherwinds", ["dkp"] = "60",},
{["itemid"] = 16918, ["itemname"] = "Bindungen des Netherwinds", ["dkp"] = "60",},
{["itemid"] = 16919, ["itemname"] = "Stiefel der Erhabenheit", ["dkp"] = "60",},
{["itemid"] = 16920, ["itemname"] = "Handschützer der Erhabenheit", ["dkp"] = "60",},
{["itemid"] = 16923, ["itemname"] = "Roben der Erhabenheit", ["dkp"] = "60",},
{["itemid"] = 16924, ["itemname"] = "Schulterstücke der Erhabenheit", ["dkp"] = "60",},
{["itemid"] = 16925, ["itemname"] = "Gürtel der Erhabenheit", ["dkp"] = "60",},
{["itemid"] = 16926, ["itemname"] = "Bindungen der Erhabenheit", ["dkp"] = "60",},
{["itemid"] = 16927, ["itemname"] = "Stiefel der Nemesis", ["dkp"] = "60",},
{["itemid"] = 16928, ["itemname"] = "Handschuhe der Nemesis", ["dkp"] = "60",},
{["itemid"] = 16931, ["itemname"] = "Roben der Nemesis", ["dkp"] = "60",},
{["itemid"] = 16932, ["itemname"] = "Schiftung der Nemesis", ["dkp"] = "60",},
{["itemid"] = 16933, ["itemname"] = "Gürtel der Nemesis", ["dkp"] = "60",},
{["itemid"] = 16934, ["itemname"] = "Armschienen der Nemesis", ["dkp"] = "60",},
{["itemid"] = 16935, ["itemname"] = "Armschienen des Drachenjägers", ["dkp"] = "60",},
{["itemid"] = 16936, ["itemname"] = "Gürtel des Drachenjägers", ["dkp"] = "60",},
{["itemid"] = 16937, ["itemname"] = "Schiftung des Drachenjägers", ["dkp"] = "60",},
{["itemid"] = 16940, ["itemname"] = "Stulpen des Drachenjägers", ["dkp"] = "60",},
{["itemid"] = 16941, ["itemname"] = "Schienbeinschützer des Drachenjägers", ["dkp"] = "60",},
{["itemid"] = 16942, ["itemname"] = "Brustplatte des Drachenjägers", ["dkp"] = "60",},
{["itemid"] = 16951, ["itemname"] = "Bindungen des Richturteils", ["dkp"] = "60",},
{["itemid"] = 16952, ["itemname"] = "Gürtel des Richturteils", ["dkp"] = "60",},
{["itemid"] = 16953, ["itemname"] = "Schiftung des Richturteils", ["dkp"] = "60",},
{["itemid"] = 16956, ["itemname"] = "Stulpen des Richturteils", ["dkp"] = "60",},
{["itemid"] = 16957, ["itemname"] = "Sabatons des Richturteils", ["dkp"] = "60",},
{["itemid"] = 16958, ["itemname"] = "Brustplatte des Richturteils", ["dkp"] = "60",},
{["itemid"] = 16959, ["itemname"] = "Armreifen des Zorns", ["dkp"] = "60",},
{["itemid"] = 16960, ["itemname"] = "Gürtelbund des Zorns", ["dkp"] = "60",},
{["itemid"] = 16961, ["itemname"] = "Schulterstücke des Zorns", ["dkp"] = "60",},
{["itemid"] = 16964, ["itemname"] = "Stulpen des Zorns", ["dkp"] = "60",},
{["itemid"] = 16965, ["itemname"] = "Sabatons des Zorns", ["dkp"] = "60",},
{["itemid"] = 16966, ["itemname"] = "Brustplatte des Zorns", ["dkp"] = "60",},
{["itemid"] = 19002, ["itemname"] = "Kopf von Nefarian", ["prio"] = "Tank > Melee > FFA", ["dkp"] = "0",},
{["itemid"] = 19334, ["itemname"] = "Die ungezähmte Klinge", ["prio"] = "FFA", ["dkp"] = "100",},
{["itemid"] = 19335, ["itemname"] = "Wirbelsäulenbrecher", ["prio"] = "Melee DD", ["dkp"] = "10",},
{["itemid"] = 19336, ["itemname"] = "Edelstein der arkanen Kraft", ["prio"] = "Most DKP", ["dkp"] = "0",},
{["itemid"] = 19337, ["itemname"] = "Das schwarze Buch", ["prio"] = "Most DKP", ["dkp"] = "0",},
{["itemid"] = 19339, ["itemname"] = "Edelstein des Gedankensprungs", ["prio"] = "Most DKP", ["dkp"] = "0",},
{["itemid"] = 19340, ["itemname"] = "Rune der Metamorphose", ["prio"] = "Most DKP", ["dkp"] = "0",},
{["itemid"] = 19341, ["itemname"] = "Lebensspendender Edelstein", ["prio"] = "Maintank > Tank > FFA", ["dkp"] = "0",},
{["itemid"] = 19342, ["itemname"] = "Gifttotem", ["prio"] = "Most DKP", ["dkp"] = "0",},
{["itemid"] = 19343, ["itemname"] = "Rollen des Blendenden Lichts", ["prio"] = "Most DKP", ["dkp"] = "0",},
{["itemid"] = 19345, ["itemname"] = "Aegis der Bewahrung", ["prio"] = "Most DKP", ["dkp"] = "60",},
{["itemid"] = 19346, ["itemname"] = "Drachenzahnklinge", ["prio"] = "Dagger Rouge > Melee/Hunter", ["dkp"] = "60",},
{["itemid"] = 19347, ["itemname"] = "Klaue von Chromaggus", ["prio"] = "Caster DD", ["dkp"] = "100",},
{["itemid"] = 19348, ["itemname"] = "Roter Drachenschuppenbeschützer", ["pref_class"] = "Paladin", ["dkp"] = "60",},
{["itemid"] = 19349, ["itemname"] = "Elementiumverstärktes Bollwerk", ["prio"] = "Maintank > Tank", ["dkp"] = "60",},
{["itemid"] = 19350, ["itemname"] = "Herzensbrecher", ["prio"] = "Tank > FFA", ["dkp"] = "10", ["comment"] = "Statstick"},
{["itemid"] = 19351, ["itemname"] = "Maladath, Runenverzierte Klinge des schwarzen Drachenschwarms", ["prio"] = "Fury/Sword Rouge > Rouge > Tank", ["dkp"] = "100",},
{["itemid"] = 19352, ["itemname"] = "Chromatisch gehärtetes Schwert", ["prio"] = "Sword Rouge/Fury > Dagger Rouge > FFA", ["dkp"] = "100",},
{["itemid"] = 19353, ["itemname"] = "Drachenkrallenbeil", ["prio"] = "FFA", ["comment"] = "PVP", ["dkp"] = "10",},
{["itemid"] = 19355, ["itemname"] = "Fokussierstab der Schattenschwingen", ["prio"] = "Druid/Caster", ["dkp"] = "100",},
{["itemid"] = 19356, ["itemname"] = "Stab der Schattenflamme", ["prio"] = "Caster DD", ["dkp"] = "200",},
{["itemid"] = 19357, ["itemname"] = "Herold des Leidens", ["prio"] = "FFA", ["dkp"] = "60",},
{["itemid"] = 19360, ["itemname"] = "Lok'amir il Romathis", ["prio"] = "Caster", ["dkp"] = "180",},
{["itemid"] = 19361, ["itemname"] = "Ashjre'thul, Armbrust der Pein", ["pref_class"] = "Hunter", ["dkp"] = "120",},
{["itemid"] = 19363, ["itemname"] = "Crul'shorukh, Schneide des Chaos", ["prio"] = "Fury", ["dkp"] = "80",},
{["itemid"] = 19364, ["itemname"] = "Ashkandi, Großschwert der Bruderschaft", ["prio"] = "FFA", ["dkp"] = "200",},
{["itemid"] = 19365, ["itemname"] = "Klaue des Schwarzen Drachen", ["prio"] = "FFA", ["dkp"] = "60",},
{["itemid"] = 19367, ["itemname"] = "Berührung des Drachen", ["prio"] = "FFA(no Mage)", ["dkp"] = "60",},
{["itemid"] = 19368, ["itemname"] = "Drachenodemhandkanone", ["prio"] = "Tank (Statstick) > FFA", ["dkp"] = "60",},
{["itemid"] = 19369, ["itemname"] = "Handschuhe der rapiden Evolution", ["prio"] = "Caster", ["dkp"] = "10", ["comment"] = "PVP",},
{["itemid"] = 19370, ["itemname"] = "Mantel der Pechschwingenkabale", ["prio"] = "Shadow Priest > Caster DD", ["dkp"] = "60",},
{["itemid"] = 19371, ["itemname"] = "Anhänger des gefallenen Drachen", ["prio"] = "Healer", ["dkp"] = "10",},
{["itemid"] = 19372, ["itemname"] = "Helm der unendlichen Rage", ["comment"] = "PVP", ["dkp"] = "10",},
{["itemid"] = 19373, ["itemname"] = "Schultern der Schwarzen Brut", ["prio"] = "FFA", ["dkp"] = "10",},
{["itemid"] = 19374, ["itemname"] = "Armschienen der arkanen Präzision", ["prio"] = "Caster DD", ["dkp"] = "80",},
{["itemid"] = 19375, ["itemname"] = "Mish'undare, Reif des Gedankenschinders", ["prio"] = "Caster DD > Paladin", ["dkp"] = "100",},
{["itemid"] = 19376, ["itemname"] = "Archimtiros' Ring der Abrechnung", ["prio"] = "FFA", ["dkp"] = "60",},
{["itemid"] = 19377, ["itemname"] = "Prestors Talisman der Verschwörung", ["prio"] = "FFA", ["dkp"] = "80",},
{["itemid"] = 19378, ["itemname"] = "Umhang des Brutlords", ["prio"] = "FFA", ["dkp"] = "60",},
{["itemid"] = 19379, ["itemname"] = "Neltharions Träne", ["prio"] = "Caster DD", ["dkp"] = "120",},
{["itemid"] = 19380, ["itemname"] = "Therazanes Zusammenhalt", ["pref_class"] = "Paladin / Hunter", ["dkp"] = "60",},
{["itemid"] = 19381, ["itemname"] = "Stiefel der Schattenflamme", ["prio"] = "FFA", ["dkp"] = "80",},
{["itemid"] = 19382, ["itemname"] = "Band aus reinem Elementium", ["prio"] = "Healer", ["dkp"] = "100",},
{["itemid"] = 19385, ["itemname"] = "Energieerfüllte Gamaschen", ["prio"] = "Healer", ["dkp"] = "80",},
{["itemid"] = 19386, ["itemname"] = "Elementiumdurchwirkter Umhang", ["prio"] = "Feral Tank > Tank", ["dkp"] = "60",},
{["itemid"] = 19387, ["itemname"] = "Chromatische Stiefel", ["prio"] = "DD > Tank", ["dkp"] = "80",},
{["itemid"] = 19388, ["itemname"] = "Angelistas Gespür", ["prio"] = "Caster DD", ["dkp"] = "60",},
{["itemid"] = 19389, ["itemname"] = "Gehärtete Drachenlederschulterpolster", ["prio"] = "Feral", ["dkp"] = "60",},
{["itemid"] = 19390, ["itemname"] = "Gehärtete Drachenlederhandschuhe", ["prio"] = "FFA", ["dkp"] = "30",},
{["itemid"] = 19391, ["itemname"] = "Schimmerndes Geta", ["prio"] = "FFA", ["dkp"] = "0", ["comment"] = "roll",},
{["itemid"] = 19392, ["itemname"] = "Gurt des gefallenen Kreuzfahrers", ["prio"] = "FFA", ["dkp"] = "10",},
{["itemid"] = 19393, ["itemname"] = "Gekettelter Taillenschutz des Primalisten", ["pref_class"] = "Paladin", ["dkp"] = "30",},
{["itemid"] = 19394, ["itemname"] = "Drachenkrallenschulterstücke", ["prio"] = "DD > Tank", ["dkp"] = "60",},
{["itemid"] = 19395, ["itemname"] = "Edelstein der Verjüngung", ["prio"] = "Healer", ["dkp"] = "120",},
{["itemid"] = 19396, ["itemname"] = "Gehärteter Drachenledergürtel", ["prio"] = "Feral Tank > FFA", ["dkp"] = "60",},
{["itemid"] = 19397, ["itemname"] = "Ring des Blackrock", ["prio"] = "Caster DD > Healer", ["dkp"] = "30",},
{["itemid"] = 19398, ["itemname"] = "Feuerschwingens Umhang", ["prio"] = "Melee/Hunter > Tank", ["dkp"] = "60",},
{["itemid"] = 19399, ["itemname"] = "Schwarzaschenrobe", ["prio"] = "Caster > 2nd Need", ["dkp"] = "0",},
{["itemid"] = 19400, ["itemname"] = "Feuerschwingens Griff", ["prio"] = "Caster / Healer", ["dkp"] = "60",},
{["itemid"] = 19401, ["itemname"] = "Gekettelter Beinschützer des Primalisten", ["pref_class"] = "Paladin", ["comment"] = "PVP", ["dkp"] = "10",},
{["itemid"] = 19402, ["itemname"] = "Beinschützer des gefallenen Kreuzfahrers", ["prio"] = "FFA", ["dkp"] = "60",},
{["itemid"] = 19403, ["itemname"] = "Band der erzwungenen Konzentration", ["prio"] = "Caster DD", ["dkp"] = "80",},
{["itemid"] = 19405, ["itemname"] = "Malfurions gesegnetes Bollwerk", ["prio"] = "FFA", ["comment"] = "PVP", ["dkp"] = "10",},
{["itemid"] = 19406, ["itemname"] = "Drachenfangzahn-Talisman", ["prio"] = "FFA(no Paladin)", ["dkp"] = "120",},
{["itemid"] = 19407, ["itemname"] = "Ebenholzfarbene Flammenhandschuhe", ["prio"] = "Shadow Priest > Warlock", ["dkp"] = "80",},
{["itemid"] = 19430, ["itemname"] = "Schleier des reinen Gedankens", ["prio"] = "Healer", ["dkp"] = "60",},
{["itemid"] = 19431, ["itemname"] = "Styleens verhinderter Skarabäus", ["prio"] = "Maintank > Tank", ["dkp"] = "120",},
{["itemid"] = 19432, ["itemname"] = "Kreis der angewandten Macht", ["prio"] = "FFA", ["dkp"] = "60",},
{["itemid"] = 19433, ["itemname"] = "Sandzwirngamaschen", ["prio"] = "FFA > 2nd Need", ["dkp"] = "0",},
{["itemid"] = 19436, ["itemname"] = "Umhang der drachischen Macht", ["prio"] = "FFA", ["dkp"] = "30",},
{["itemid"] = 19438, ["itemname"] = "Ringos Blizzardstiefel", ["pref_class"] = "Mage", ["dkp"] = "100",},
{["itemid"] = 19439, ["itemname"] = "Geflochtener Schattenwams", ["prio"] = "FFA", ["dkp"] = "0", ["comment"] = "roll",},
{["itemid"] = 19362, ["itemname"] = "Schneide der Verdammnis", ["prio"] = "FFA", ["dkp"] = "30",},
{["itemid"] = 19434, ["itemname"] = "Band der dunklen Herrschaft", ["prio"] = "Shadow Priest / Warlock", ["dkp"] = "80",},
{["itemid"] = 19354, ["itemname"] = "Drachischer Rächer", ["prio"] = "FFA", ["dkp"] = "0", ["comment"] = "roll",},
{["itemid"] = 19437, ["itemname"] = "Stiefel des reinen Gedankens", ["prio"] = "Healer", ["dkp"] = "100",},
{["itemid"] = 19435, ["itemname"] = "Essenzsammler", ["prio"] = "FFA", ["dkp"] = "0", ["comment"] = "roll",},
{["itemid"] = 19358, ["itemname"] = "Drachischer Schlägel", ["prio"] = "Feral", ["dkp"] = "100",},
}
